spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.108.10.232:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/vueblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: tl20010213
    hikari:
     connection-timeout: 600000
     maxLifeTime: 80000
     maximum-pool-size: 500
     minimum-idle: 20
     validation-timeout: 3000
     idle-timeout: 60000
  redis:
    host: 39.108.10.232
    port: 6379
    database: 1
    password:
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 30
        max-wait: -1
        max-idle: 8
        min-idle: 0
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    # 连接池中的最大空闲连接
    # 连接池中的最小空闲连接
    timeout: 5000
  quartz:
  # 将任务等保存化到数据库
#    job-store-type: jdbc
    job-store-type: memory
    # 程序结束时会等待quartz相关的内容结束
    wait-for-jobs-to-complete-on-shutdown: true
    # QuartzScheduler启动时更新己存在的Job,这样就不用每次修改targetObject后删除qrtz_job_details表对应记录
    overwrite-existing-jobs: true
    # 这里居然是个map，搞得智能提示都没有，佛了
    properties:
      org:
        quartz:
#          # scheduler相关
#          jdbc:
#            initialize-schema: always
#            schema: classpath:schema/tables_mysql
          # 线程池相关
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            # 线程数
            threadCount: 10
            # 线程优先级
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8081
  tomcat:
   uri-encoding: UTF-8
  servlet:
   context-path: /api
zzzyuan:
    jwt:
      secret: 1a2b3c4d5gtl666xq88
      expire: 604800
      header: Authorization
shiro-redis:
        enabled: true
        redis-manager:
          host: 39.108.10.232:6379
          password: 123456


